# config file for ByteCart bukkit plugin.

# set true if you want a lot debug messages on the console
debug: false

# set false to disable hostname resolution
hostname_resolution: true

# the name of the database for hostname resolution
# default : BCHostnames
database: BCHostnames

# choose the sql database type for hostname resolution: mysql or sqllite
sql: sqllite

# set false if you don't want to load chunks automatically around a moving cart
loadchunks: true

# set true if you want minecarts keep their velocity without boosters
constantspeed: false

# Force players to provide books to get tickets when needed
# set to false if you want the plugin to automatically create books when needed
mustProvideBooks: false

# If possible, reuse an existing ticket found in players inventory
# set to false to create a new ticket each time a player request one
reusetickets: true

# Set to true to drop items on the ground when removing carts with BC7008
# Set to false to remove them. They will be lost forever.
keepitems: true

# Minecraft 1.8 has a bug that removes all brackets in signs 
# Set to true to fix brackets in signs if your signs are broken 
FixBroken18: false

# Set to true to enable the old behaviour of BC9000 i.e BC9000 as closing sign of subtrack
# if false, BC9000 can be used anywhere without breaking updater configuration
# if true, BC9000 can be used only to close subtrack.
# default : false
oldBC9000behaviour: false

# Name to use as author of ticket book
author: ByteCart

# Title of ticket book
title: Ticket to

# Enable dynmap support
dynmap: true

# Name of Dynmap layer
dynmap.layer: ByteCart

# timeout of updaters in minutes
# set to 0 for no timeout
updater.timeout: 60

# initial value of time-to-live
# number of routers that a cart may cross
# before going to recycling center.
# this is to prevent loops.
TTL.value: 64

# initial speed of minecarts
BC7001.startvelocity: 2

# Address where empty carts or empty storage carts
# will be routed.
# Default : 0.0.0
EmptyCartsDefaultRoute: 0.0.0

# Address where players with no ticket
# will be routed.
# Default : 0.0.0
PlayersNoTicketDefaultRoute: 0.0.0

# error messages
Error.SetAddress: Error - too few/many items in inventory
#Error.SetAddress: Erreur - Pas assez/trop d'elements dans l'inventaire

#Info messages

Info.SetAddress: New destination address
#Info.SetAddress: Nouvelle destination

Info.SetReturnAddress: New return address
#Info.SetReturnAddress: Nouvelle adresse de retour

Info.SetAddress2: Don't touch your inventory
                  Take a cart and have a nice trip !
#Info.SetAddress2: Ne touchez pas a votre inventaire
#                  Prenez un cart et bonne route !

Info.RightClickCart: Right-click on a storage cart to select it
#Info.RightClickCart: Clic droit sur un storage cart pour le selectionner

#Updater
Info.SetUpdater: "This cart is now an Updater !"

Info.GetTTL: "Routers to cross : up to "
#Info.GetTTL: "nb max de routeurs :"

Info.BC8010_region: On the way to region
#Info.BC8010_region: En route pour la region

Info.BC8010_Track: You are entering track
#Info.BC8010_track: Vous entrez sur la voie

Info.Destination: You are arrived at
#Info.Destination: Vous etes arrive a